---
title: "Home work 6"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r libraries, include=FALSE}
#library(devtools)
#devtools::install_github("timelyportfolio/d3treeR", force = TRUE)
#library(d3treeR)
library(flexdashboard)
library(tidyverse)
library(janitor)
library(plotly)
library(forcats)
library(treemap)
library(viridis)
```

```{r data_import_cleaning_problem2, include=FALSE}
data_instacart = 
  read_csv("../data/instacart_train_data.csv.zip") %>%
  clean_names()

# unique departments
departmet_u = 
  data_instacart %>%
  select(department) %>%
  distinct()

top_products =
  data_instacart %>%
  filter(department == "produce") %>%
  count(product_name) %>% 
  arrange(desc(n)) %>%
  head(10) 
  
top_products = inner_join(top_products, data_instacart)  
```



Row 
-----------------------------------------------------------------------

### Visualize product demand   
```{r, eval=FALSE}
data_instacart %>% 
  group_by(department, aisle) %>%
  summarize(n = n()) %>% 
  treemap(index = c("department", "aisle"), vSize = n, type = "index") %>% 
  d3tree(rootname = "General")
```

```{r}
p =
  data_instacart %>% 
  filter(!is.na(days_since_prior_order)) %>%
  filter(department == "produce") %>%
  count(product_name) %>% 
  arrange(desc(n)) %>%
  head(5) %>%
  inner_join(x = data_instacart, y = .) %>% 
  ggplot(aes(x = add_to_cart_order, y = days_since_prior_order, group = product_name, color = product_name)) +
  geom_smooth(se = FALSE) +
  #scale_color_viridis(discrete = TRUE) +
  #coord_cartesian() +
  theme_classic()

  ggplotly(p)
  
  
  #plot_ly(x = ~add_to_cart_order, y = ~days_since_prior_order,
          #color = ~order_hour_of_day, alpha = 0.5, 
          #type = "scatter", mode = "marker")
```


Row
-----------------------------------------------------------------------

### Barpot of top items in a department  
```{r barplot}
# numeric input = display top n
# filter by department 
# produce department has the most items
data_instacart %>%
  filter(department == "produce") %>%
  count(product_name) %>% 
  arrange(desc(n)) %>%
  head(10) %>%
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, 
          type = "bar")
```


### Boxplot of order hour of the day for top items in a department  

```{r boxplot}
top_products %>%
  mutate(product_name = fct_reorder(product_name, order_hour_of_day, IQR)) %>% 
  plot_ly(x = ~product_name, y = ~ order_hour_of_day, color = ~product_name,
          colors = "Set2",
          type = "box")
```

