---
title: "Interactive exploratory analysis of instacart top selling products"
---
<br>

### [Istacart dataset](http://jeffgoldsmith.com/DSI/dataset_instacart.html) used for this exercise had 1384617 observations and 15 variables. 

<br>

### Flexdashboard for _produce_ department
Produce department had the most products purchased. I created a flexdashboard to conduct exploratory analyses of that department by evaluating the following:

* Product demand in each aisle of _produce_ department, based on the number of items purchased;  

* Relationship between days since the last order and the order in which an order was added to the cart for top 5 items from _produce_ department. My hypothesis is that the relationship will have a negative association (the item which hasnt been purchased for longer time would go into the cart first);    

* Barpot of top 10 items in _produce_ department;  

* Boxplot of order hour of the day for top 10 items in _produce_ department.  

<br>

### Shiny dashboard was created to explore data in the fashion of *flexdashboard* but with flexibility to conduct the visualization for **any** department`s **top n** products.  
